import { Octokit } from '@octokit/rest';

function api() {
  if (!process.env.GITHUB_TOKEN) throw new Error('GITHUB_TOKEN is missing');
  return new Octokit({ auth: process.env.GITHUB_TOKEN });
}

export async function publishRepository(job, files) {
  const octokit = api();
  const owner = process.env.GITHUB_OWNER;
  if (!owner) throw new Error('GITHUB_OWNER is missing');
  let repository;
  try {
    ({ data: repository } = await octokit.rest.repos.createForAuthenticatedUser({
      name: job.project_name,
      private: job.private_repo,
      auto_init: true,
      description: 'Generated by AI Agent Site Builder'
    }));
  } catch (error) {
    if (error.status !== 422) throw error;
    ({ data: repository } = await octokit.rest.repos.get({ owner, repo: job.project_name }));
  }

  // Wait for the initialized branch to become available.
  let head;
  for (let i = 0; i < 8; i += 1) {
    try {
      ({ data: head } = await octokit.rest.git.getRef({ owner, repo: repository.name, ref: 'heads/main' }));
      break;
    } catch (error) {
      if (error.status !== 409 && error.status !== 404) throw error;
      await new Promise((resolve) => setTimeout(resolve, 1000));
    }
  }
  if (!head) throw new Error('GitHub repository was created but main branch is not ready');
  const { data: commit } = await octokit.rest.git.getCommit({ owner, repo: repository.name, commit_sha: head.object.sha });
  const tree = files.map((file) => ({ path: file.path, mode: '100644', type: 'blob', content: file.content }));
  const { data: newTree } = await octokit.rest.git.createTree({ owner, repo: repository.name, base_tree: commit.tree.sha, tree });
  const { data: newCommit } = await octokit.rest.git.createCommit({
    owner,
    repo: repository.name,
    message: 'Generate website with AI Site Builder',
    tree: newTree.sha,
    parents: [head.object.sha]
  });
  await octokit.rest.git.updateRef({ owner, repo: repository.name, ref: 'heads/main', sha: newCommit.sha, force: false });
  return { owner, repo: repository.name, url: repository.html_url, commit: newCommit.sha };
}
